spring:
  application:
    name: spring-world

  ## DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/mycommunity
    username: dev
    password: 5500

## JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ture
        show_sql: true
    hibernate:
      ddl-auto: update